version: "1" # version of compose format

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  books-service:
    build: ./books # path is relative to docker-compose-shorthand.yml location
    volumes:
      - type: bind
        source: ./books #host directory
        target: /usr/src/app # container directory
    environment:
      - MONGO_URL=mongodb://mongodb:27017/BooksDB
    ports:
      - "5001:8001" # host:container
    depends_on:
      - "mongodb"
  loans-service:
    build: ./loans # path is relative to docker-compose-shorthand.yml location
    volumes:
      - type: bind
        source: ./loans #host directory
        target: /app # container directory
    environment:
      - MONGO_URL=mongodb://mongodb:27017/LoansDB
    ports:
      - "5002:8002" # host:container
    depends_on:
      - "mongodb"
      - "books-service"

  # nginx:
  #   image: nginx:latest # pulling image from DockerHub
  #   ports:
  #     - "80:80" # host:container
  #   volumes:
  #     - type: bind
  #       source: ./nginx.conf # host directory
  #       target: /etc/nginx/nginx.conf # container directory
