version: "1" # version of compose format

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
  books-service:
    build: ./books # path is relative to docker-compose-shorthand.yml location
    restart: always # always restart the container
    volumes:
      - type: bind
        source: ./books #host directory
        target: /usr/src/app # container directory
    environment:
      - MONGO_URL=mongodb://mongo:27017/BooksDB
      - PORT=80
    ports:
      - "5001:80" # host:container
    expose:
      - 80
    depends_on:
      - "mongo"

  loans-service:
    build: ./loans # path is relative to docker-compose-shorthand.yml location
    restart: always # always restart the container
    volumes:
      - type: bind
        source: ./loans #host directory
        target: /app # container directory
    environment:
      - MONGO_URL=mongodb://mongo:27017/LoansDB
    ports:
      - "5002:80" # host:container
    expose:
      - 80
    depends_on:
      - "mongo"
      - "books-service"

  loans-service-2:
    build: ./loans # path is relative to docker-compose-shorthand.yml location
    restart: always # always restart the container
    volumes:
      - type: bind
        source: ./loans #host directory
        target: /app # container directory
    environment:
      - MONGO_URL=mongodb://mongo:27017/LoansDB
    ports:
      - "5003:80" # host:container
    expose:
      - 80
    depends_on:
      - "mongo"
      - "books-service"

  nginx:
    build: ./proxy
    restart: always # always restart the container
    ports:
      - "80:80" # host:container
    expose:
      - 80
    depends_on:
      - "books-service"
      - "loans-service"
      - "loans-service-2"
